behaviors:
  RabbitBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 15
      buffer_size: 150
      learning_rate: 4.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 32
    summary_freq: 10000